# Generated by Django 3.2 on 2022-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_ready',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
