# Generated by Django 3.2 on 2022-08-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_ready',
        ),
    ]
