# Generated by Django 3.2 on 2022-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_status',
            field=models.CharField(choices=[('READY', 'Ready to Move In'), ('MORTGAGE', 'Mortgage Plan / OffPlan')], default='READY', max_length=9),
        ),
    ]
