# Generated by Django 4.1 on 2022-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_handOver_in_12_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_villas_and_mansionettes',
            field=models.BooleanField(default=False),
        ),
    ]
