# Generated by Django 4.1 on 2022-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_state_remove_listing_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='city',
            new_name='area',
        ),
        migrations.AddField(
            model_name='listing',
            name='project',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
