# Generated by Django 4.1 on 2022-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_city_listing_area_listing_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
    ]
