# Generated by Django 4.1 on 2022-08-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='project',
            new_name='developer',
        ),
    ]
