# Generated by Django 4.1 on 2022-08-27 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_br_1_listing_br_10_listing_br_2_listing_br_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='BR_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_10',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_7',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_8',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='BR_9',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='studio',
        ),
        migrations.CreateModel(
            name='Floor_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField(blank=True)),
                ('is_studio', models.BooleanField(default=False)),
                ('price_sqft', models.IntegerField(blank=True)),
                ('from_sqft', models.IntegerField(blank=True)),
                ('min_price', models.IntegerField(blank=True)),
                ('floor_plan_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
