# Generated by Django 4.1 on 2022-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_listing_br_1_remove_listing_br_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor_plan',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floor_plan',
            name='from_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floor_plan',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floor_plan',
            name='price_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
