# Generated by Django 4.1 on 2022-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_amenities_listing_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
