# Generated by Django 3.2 on 2022-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20220903_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor_plan',
            name='from_sqft',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='floor_plan',
            name='min_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='floor_plan',
            name='price_sqft',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
